language: ruby
gemfile:
  - Gemfile
rvm:
  - 1.9.3
  - 2.0.0
notifications:
  email: false
bundler_args: --without development
services: mongodb
matrix:
  include:
    - rvm: jruby-19mode
      gemfile: Gemfile
      env: JRUBY_OPTS="--server -Xcompile.invokedynamic=false -J-XX:+TieredCompilation -J-XX:TieredStopAtLevel=1 -J-noverify -J-Xms512m -J-Xmx1024m"
