gemfile:
  - Gemfile
  - gemfiles/rails3_0.gemfile
  - gemfiles/rails3_1.gemfile
  - gemfiles/rails4_0.gemfile
language: ruby
rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0
notifications:
  email: false
bundler_args: --without development
services: mongodb
matrix:
  exclude:
    - rvm: 1.8.7
      gemfile: gemfiles/rails4_0.gemfile