gemfile:
  - Gemfile
  - gemfiles/rails3_1.gemfile
  - gemfiles/rails3_2.gemfile
language: ruby
rvm:
  - 1.8.7
  - ree
  - 1.9.3
notifications:
  email: false
bundler_args: --without development
services: mongodb
